
@rootApi = http://localhost:8000
### server testing
@userApi = {{rootApi}}/api/v1/user

###
@burrowApi = {{rootApi}}/api/v1/burrow

GET {{rootApi}}

#### GETuser
GET {{userApi}}


#### CXREATE USER
POST  {{userApi}}
Content-Type: application/json

{
    "role": "student",
    "fName": "Robert",
    "lName": "Smith",
    "phone":"09488",
    "address": "WAATERLOO",
    "email": "emil@11",
    "password": "1234"
    
}

//Burrow api
###
POST ({{{burrowApi}}}
Content-Type: application/json

{
    "bookId" :"skjfo9844",
    "BookName": "Ashish",
    "thumnbnail": "http://....",
    "userId": "addjjdj2344",
    "userName": "How to code",
    "returnedDate": "23 jan"

}